export const sampleVideo = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";

export const anime = [
  {
    id: "neon-ronin-zero",
    title: "Neon Ronin Zero",
    genre: "Action",
    studio: "Northline Works",
    rating: "PG-13",
    year: "2026",
    episodes: 12,
    duration: "24m",
    progress: 38,
    currentEpisode: 1,
    description:
      "A fugitive swordswoman and an exiled broadcast engineer race through a city where memories are bought as entertainment.",
    poster: "linear-gradient(145deg, #17213a, #ff4f67 48%, #2ce6d3)",
  },
  {
    id: "signal-bloom",
    title: "Signal Bloom",
    genre: "Sci-Fi",
    studio: "Glass Harbor",
    rating: "TV-14",
    year: "2025",
    episodes: 10,
    duration: "23m",
    progress: 72,
    currentEpisode: 7,
    description: "Students decode flowers that transmit messages from a vanished orbital garden.",
    poster: "linear-gradient(145deg, #11131b, #8d7cff 48%, #7be495)",
  },
  {
    id: "moonlit-bento-club",
    title: "Moonlit Bento Club",
    genre: "Slice of Life",
    studio: "Soft Rail",
    rating: "TV-PG",
    year: "2026",
    episodes: 8,
    duration: "22m",
    progress: 44,
    currentEpisode: 3,
    description: "A midnight cooking club turns quiet meals into tiny acts of courage.",
    poster: "linear-gradient(145deg, #2b1d35, #f6c85f 52%, #ff8f5a)",
  },
  {
    id: "cloud-atelier",
    title: "Cloud Atelier",
    genre: "Fantasy",
    studio: "Mira Frame",
    rating: "TV-PG",
    year: "2024",
    episodes: 24,
    duration: "25m",
    progress: 51,
    currentEpisode: 11,
    description: "A weather painter apprentices under an impatient sky architect above the floating provinces.",
    poster: "linear-gradient(145deg, #1f4a5a, #f4f7fb 42%, #8d7cff)",
  },
  {
    id: "after-school-orbit",
    title: "After School Orbit",
    genre: "Sci-Fi",
    studio: "Copper Lens",
    rating: "TV-14",
    year: "2025",
    episodes: 13,
    duration: "24m",
    progress: 18,
    currentEpisode: 2,
    description: "A school astronomy team discovers their observatory has been steering a hidden satellite.",
    poster: "linear-gradient(145deg, #071014, #2ce6d3 44%, #f6c85f)",
  },
  {
    id: "iron-kitsune-court",
    title: "Iron Kitsune Court",
    genre: "Action",
    studio: "Red Gate Motion",
    rating: "TV-14",
    year: "2026",
    episodes: 16,
    duration: "24m",
    progress: 29,
    currentEpisode: 5,
    description: "A disgraced guard protects a mechanical shrine through tournament season.",
    poster: "linear-gradient(145deg, #241318, #ff4f67 45%, #f6c85f)",
  },
  {
    id: "paper-lantern-files",
    title: "Paper Lantern Files",
    genre: "Mystery",
    studio: "Indigo Desk",
    rating: "TV-14",
    year: "2026",
    episodes: 9,
    duration: "24m",
    progress: 8,
    currentEpisode: 1,
    description: "A junior archivist investigates impossible case files hidden in festival lanterns.",
    poster: "linear-gradient(145deg, #14171f, #b9d96d 42%, #ff4f67)",
  },
  {
    id: "starfall-railway",
    title: "Starfall Railway",
    genre: "Fantasy",
    studio: "Harbor Nine",
    rating: "TV-PG",
    year: "2025",
    episodes: 18,
    duration: "25m",
    progress: 63,
    currentEpisode: 9,
    description: "A conductor-in-training guides a night train that collects fallen stars before dawn.",
    poster: "linear-gradient(145deg, #0a1020, #2ce6d3 38%, #8d7cff)",
  },
];

export const genres = ["All", "Action", "Fantasy", "Slice of Life", "Sci-Fi", "Mystery"];

export const schedule = [
  ["Mon", "Moonlit Bento Club"],
  ["Wed", "Signal Bloom"],
  ["Fri", "Neon Ronin Zero"],
  ["Sun", "Cloud Atelier"],
];
